baseURL = "/"
footnoteReturnLinkContents = "↩"
title = "HKL's Notes"
pagination.pagerSize = 10
theme = "lighthouse100-theme"

[params]
  AuthorName = "Kunlun HUANG"
  GitHubUser = "hkwk"
  SidebarRecentLimit = 5
  Subtitle = "Just record things."
  Comments = "Cares"
  homepageurl = "https://xou.net/"
  IssueURL = "https://github.com/hkwk/hkwk.github.io/issues"
  LinkedinUser = "huangkl"
  CVurl = "https://hkl.ac.cn"
  MIITBEIAN = "粤ICP备13053581号-7"
  GABEIAN = " "
  hugoVersion = "0.147.7"

[permalinks]
  post = "/:year/:month/:slug/"
  pages = "/page/:contentbasename"

