baseURL = "/"
footnoteReturnLinkContents = "↩"
title = "HKL's Notes"
pagination.pagerSize = 10
theme = "lighthouse100-theme"
languageCode = "zh-CN"

[params]
  AuthorName = "Kunlun HUANG"
  GitHubUser = "hkwk"
  SidebarRecentLimit = 5
  Subtitle = "Just record things."
  Comments = "Cares"
  homepageurl = "https://xou.net/"
  IssueURL = "https://github.com/hkwk/hkwk.github.io/issues"
  LinkedinUser = "huangkl"
  CVurl = "https://hkl.ac.cn"
  MIITBEIAN = "粤ICP备13053581号-7"
  GABEIAN = "粤公网安备44011302004954号"
  hugoVersion = "0.147.7"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[permalinks]
  post = "/:year/:month/:slug/"
  pages = "/page/:contentbasename"

